spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT
    username: root 
    password: root 

# actable:
#   table:
#     auto: update
#   model:
#     pack: com.applecat.blog.model.pojo
#   database:
#     type: mysql

# mybatis:
#   mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

logging:
  level:
    root: info
    com.applecat: debug 
  file: 
    path: log/blog-dev.log